version: "3.9"

services:

  postgres:
    image: postgres:13
    container_name: postgres_bank
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bank
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    image: main:latest
    container_name: main
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/bank
      - PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres-data:
